### ISSUE TITLE
Dropdowns and modals have the scroll bar jump issue

### ISSUE THREAD

**Issue by ScotsScripts** [imperavi/kube#35]
Is there any way to fix the problem of the scrollbar disappearing and having the page jump to the right? Here are a couple examples from the KUBE support page:

Drodown: http://imperavi.com/kube/tools/js-dropdown/

Go to any dropdown on this page, open it, then hover on one of the options. The scrollbar disappears and the whole page shifts to the right.

Same with modals: http://imperavi.com/kube/tools/js-modal/

Open the model, the scrollbar disappears and the page jumps to the right.

**Comment by cihadturhan** [comment]
These two lines causing the problem

https://github.com/imperavi/kube/blob/master/js/dropdown.js#L197-L198

but I have no idea why @imperavi wanted to prevent body scroll for dropdowns. 

You have to prevent scroll when modal appears and that's why scrollbar disappears. Same happens for [Bootstrap](http://getbootstrap.com/javascript/#modals) and [UIkit](http://getuikit.com/docs/modal.html). However, they prevent jump with different solutions. UIkit adds a dummy scrollbar and Bootstraps adds `padding-right: 17px;` rule when scrollbar appears

**Comment by ScotsScripts** [comment]
Is removing those two lines a good solution?

**Comment by cihadturhan** [comment]
Well, for me it's ok to remove it for drop-down but not modals. I just checked on the demo page. However, it's better to see an answer from @imperavi . I might be missing something.

**Comment by wdebusschere** [comment]
Same problem here, but i don't notice the problem on the imperavi site..

**Comment by wdebusschere** [comment]
Kind of a fix:

	
	this.$dropdown.on('mouseover', function() { $('html').css('overflow', 'hidden'); });
		this.$dropdown.on('mouseover', function() { $('html').css('padding-right', '15px'); });

			this.$dropdown.on('mouseout', function() { $('html').css('overflow', ''); });
			this.$dropdown.on('mouseout', function() { $('html').css('padding-right', '0px'); });

**Comment by chieakiba** [comment]
I know this is a closed issue but I'm getting the same scrollbar jumping issue when I use a dropdown. I tried the function the person above suggested but it doesn't seem to work for me
