### ISSUE TITLE
Old Kube docs?

### ISSUE THREAD

**Issue by believer-ufa** [imperavi/kube#67]
Sorry, but we using Kube CSS Framework v5 in our project. Can you place this old docs in some page?

**Comment by Eleisonchr** [comment]
I'm implementing Kube in some projects in development stage. But I afraid now, because feel me abandoned, I use Less, new Kube uses scss, fortunately the projects that I use kube still are not finished and permit to choose other css framework. It's a shame because the Kube was serving me very well, but without reference, other css tech (Less to Scss)  and with fear is difficult to invest in the project. Please provide oldest doc, encouraging to migrate to new. Not removing the old doc that will cause users to migrate to the new.

**Comment by invasoria** [comment]
Here's a an archive version of the v5 documentation:
http://web.archive.org/web/20160318171700/https://imperavi.com/kube/css/
